#cloud-config

package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - curl
runcmd:
  - sysctl -p /etc/sysctl.d/99-tailscale.conf
  - curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up ${tailscale_up_args}
timezone: UTC
write_files:
  - path: /etc/sysctl.d/99-tailscale.conf
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
