name: Add node
on:
  workflow_dispatch:
    inputs:
      region:
        description: Deployment region
        required: true
        default: ash
        type: choice
        options:
          - nbg1
          - hel1
          - ash
          - hil
          - sin
      size:
        description: Node size
        required: true
        default: cpx11
        type: choice
        options:
          - cpx11
          - cpx21
          - cpx31
permissions:
  contents: write
jobs:
  add_to_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add nodes
        uses: mikefarah/yq@master
        with:
          cmd: "yq -i '. + {\"region\":\"${{ inputs.region }}\", \"size\": \"${{ inputs.size }}\"}' ./stacks/prod/ephemeral-tailscale-nodes/nodes.yaml"

      - uses: EndBug/add-and-commit@v9
        with:
          message: "ci: add new ${{ inputs.size }} node to ${{inputs.region }}"
          default_author: github_actions
          add: |
            - ./stacks/prod/ephemeral-tailscale-nodes/nodes.yaml
